# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [2]:
import numpy as np
a = np.random.random(size=(4, 7)) * 20
a -= np.amin(a)
a /= np.amax(a)
a

array([[0.46408732, 0.46270245, 0.43406064, 0.63271254, 0.2439659 ,
        0.34858759, 0.74136329],
       [0.35927387, 0.82333068, 0.08985527, 0.71274509, 0.89029078,
        0.32598042, 0.64296113],
       [0.5294862 , 1.        , 0.43313687, 0.        , 0.76786253,
        0.5609004 , 0.43265094],
       [0.8391484 , 0.42283193, 0.89486459, 0.10338802, 0.61607012,
        0.09358932, 0.38561385]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [3]:
import numpy as np
a = np.random.randint(size=(8, 10), low=0, high=11)
print(a)
mn, mni = np.sum(a[0]), 0
for i in range(1, 8):
    if np.sum(a[i]) < mn:
        mn = np.sum(a[i])
        mni = i
print(f"Строка: {a[mni]} Индекс: {mni}")

[[ 8  1  4  3  4  7  3  1  2  5]
 [ 7  8  2  6 10  6  0 10  1  1]
 [ 3  0  0 10  2  4  1  6  2  3]
 [ 8  8  2  2  7  3  9  6  2  5]
 [ 4  7  4  7  2  7  9  4  1  1]
 [ 7  2  8  3  3 10  2  2  6  0]
 [ 0  1  8  2 10  0 10  7  1  7]
 [ 8  3  0  8  8  5  5  5  1  1]]
Строка: [ 3  0  0 10  2  4  1  6  2  3] Индекс: 2


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [4]:
point_1 = np.array([1, 2, 2])
point_2 = np.array([5, 6, 2])
res = np.sqrt((point_1[0] - point_2[0])**2 + (point_1[1] - point_2[1])**2 + (point_1[2] - point_2[2])**2)
print(res)

5.656854249492381


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [5]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
С = np.array([[7, 21], [11, 8], [8, 4]])
С *= -1
X = np.dot(np.linalg.inv(A), С)
X = np.dot(X, np.linalg.inv(B))
print(X)

[[ 1.00000000e+00  5.55111512e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [6]:
data = np.loadtxt(fname="minutes_n_ingredients.csv", dtype="int32", delimiter=",")
# id,minutes,n_ingredients
print(data[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [7]:
mn = np.amin(data[:, 1:], axis=0)
mx = np.amax(data[:, 1:], axis=0)
md = np.median(data[:, 1:], axis=0)
ar = np.mean(data[:, 1:], axis=0)
print(f"среднее значение: {ar}")
print(f"минимальное значение: {mn}")
print(f"максимальное значение: {mx}")
print(f"медиана: {md}")

среднее значение: [2.16010017e+04 9.05528000e+00]
минимальное значение: [0 1]
максимальное значение: [2147483647         39]
медиана: [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [8]:
q = np.quantile(data[:, 1], .75)
data[data[:, 1] > q] = q
data

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [    65,     65,     65]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [9]:
count = np.sum(data[:, 1] == 0)
data[data[:, 1] == 0] = 1
count

479

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [10]:
print(len(np.unique(data[:, 0])))

74984


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [11]:
print(np.unique(data[:, 2]))
print(len(np.unique(data[:, 2])))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 33 34 65]
33


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [12]:
a = data[data[:, 2] <= 5]
print(a)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [13]:
s = max(data[:, 2] / data[:, 1])
print(s)

23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [14]:
sor = data[data[:, 1].argsort()][::-1]
print(np.mean(sor[:100, 2]))

61.12


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [15]:
data[np.random.choice(data.shape[0], size=10)]



array([[265188,     20,      5],
       [ 13390,     10,      5],
       [162205,     35,      9],
       [218874,     40,      5],
       [200574,     45,     10],
       [367831,     20,     10],
       [177000,     55,     10],
       [457529,     50,     10],
       [    65,     65,     65],
       [    65,     65,     65]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [16]:
md = np.average(data[:, 2])
print(f"{np.sum(data[:, 2] < md) / len(data) * 100}%")



75.345%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [17]:
new_data = data.copy()
new_data = np.append(new_data, np.logical_and(new_data[:, 1] <= 20, new_data[:, 2] <= 5).astype(int)[:,None], axis=1)
new_data



array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [    65,     65,     65,      0]])

13. Выведите процент "простых" рецептов в датасете

In [18]:
print(f"{np.sum(new_data[:, 3] == 1) / len(new_data) * 100}%")

9.943%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [19]:
# 1 - короткий, 2 - стандартный, 3 - длинный рецепт

sr1 = data[data[:, 1] < 10]
sr2 = data[np.logical_and(10 <= data[:, 1],  data[:, 1]< 20)]
sr3 = data[data[:, 1] >= 20]
x = min(sr1.shape[0], sr2.shape[0], sr3.shape[0])
sr1 = sr1[:x, :]
sr2 = sr2[:x, :]
sr3 = sr3[:x, :]
res = np.array([sr1, sr2, sr3])
print(res)

[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [     1      1      1]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [168901     25      7]
  [392339     35     13]
  [206732     45     10]]]
